# Array Creation in NumPy

In [4]:
EXP : 5

In [6]:
#Aim : Creating Array using Numpy

In [8]:
#Name: Aman H. Mahalle 
#Roll No.:73
#Sec: C
#Subject:ET - 1

In [1]:
import numpy as np


In [2]:
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d)


[1 2 3 4 5]


In [3]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)


[[1 2 3]
 [4 5 6]]


In [28]:
zeros_array = np.zeros((3, 3))
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [30]:
ones_array = np.ones((2, 4))
print(ones_array)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [32]:
range_array = np.arange(0, 10, 2)  # Start, stop, step
print(range_array)

[0 2 4 6 8]


In [34]:
random_array = np.random.rand(3, 3)
print(random_array)


[[0.89743244 0.43720833 0.39334732]
 [0.32787296 0.82278559 0.73122355]
 [0.37835969 0.14104503 0.20597111]]
